### PR TITLE
Fix setup

### LINKED ISSUE #5: Restructure project files
Currently, users must pollute their `PYTHONPATH` to setup sem_python. This can introduce all sorts of subtle bugs in this project as well as any other projects on a users machine. Additionally, a few inconveniences that the current setup has that can be easily avoided (e.g. users have to manually install dependancies, local scripts cannot be called from arbitrary locations, etc.)

I would like to implement a more canonical python project structure using [setuptools](https://setuptools.readthedocs.io/en/latest/). This will simplify the installation and development process for the project, and make it more pythonic :wink:

### PR DESCRIPTION
**Pull request by andfranklin**
Changes the installation procedure for users and developers so they no longer have to adjust their `PYTHONPATH`. No functional changes to the code were made.

Closes #5

### CODE REVIEW

**Comment by ghost** [comment]
For the most part, I like these changes. However, a few things:

- `python setup.py test` requires `sudo` because permission is denied for writing to `sem_python.egg-info/requires.txt`
- Test suite no longer runs in color - you'll see a package called `colour-runner` being used by the current test script. The color is important to me because it's very difficult for me to read otherwise, and I run the test suite a lot.
- The `build` and `dist` directories need to be ignored by git.
- Is the `src/` to `sem_python/` change something that is required by packages? It seems like `src/` is a better name to me.
- Is `python setup.py test` our only option for running the test suite? It seems weird to call the setup script to run tests.
- I made another commit since you branched from master. You'll need to rebase your changes. It may or may not be complicated due to your renaming of `src/`. All I've done in that commit is rename `Postprocessor` to `Output`.

**Comment by andfranklin** [comment]
- Hmmm, I've never needed `sudo` when running the tests. It might be an operating system dependent thing, or because you are using your system's default installation of python. What OS are you using?
- Yes, I noticed that. So I could spend time trying to figure-out how to get `colour-runner` working with `setup.py`. Or, I was thinking that we could use [pytest](https://docs.pytest.org/en/latest/). They have a nice printout, and writing tests is much nicer than using unittest. It's suppose to work out of the box with unittest, so I don't think any of the tests would need to be rewritten. Here is an example of the test printout: [link](https://docs.pytest.org/en/latest/example/reportingdemo.html). Note, their example does not display the colors that you would see in the terminal.
- I just added `build` and `dist` to the `.gitignore`. I don't know if you noticed at the bottom of the README this command: `pip install -e .`? You will definitely want to do this if you will be making changes to the code. This will help you avoid having to uninstall and install the package each time you make a change.
- It is not required to rename `src/` to `sem_python/`, but it is [recommended](https://packaging.python.org/tutorials/distributing-packages/#your-package) (clunky as it may be). I tried to naively rename `sem_python/` to `src/` and I received errors when testing. I think there are workarounds, but I don't know if it is worth it.
- You could do something like: `python2 -m unittest discover testing -p "*Tester.py"`, but I don't think that's what you're looking for. I think they do that because it's easier to setup continuous integration and manage packages on pypi.
- Thanks for the heads-up.

**Comment by andfranklin** [comment]
With regards to the `src` or `sem_python` directory issue -- I found a recent blog post recommending the use of a `src` directory: [link](https://hynek.me/articles/testing-packaging/). So, yes -- all of the code can be contained within a directory named `src`. The catch is that there is still a directory within `src` that is named `sem_python`. This seems even clunkier than just having a top-level directory called `sem_python`, but the blog post explains that there are some benefits.

**Comment by andfranklin** [comment]
So, I'm rebasing my branch on the most current version of `master`. When I run the tests I get the following 5 failures:

```
======================================================================
ERROR: test (testing.tests.derivatives.aux.DensityDerivativesTester.DensityDerivativesTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/DensityDerivativesTester.py", line 23, in test
    rel_diffs = self.derivatives_tester.checkDerivatives(test_aux, other_aux, root_vars)
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/AuxDerivativesTester.py", line 31, in checkDerivatives
    aux.compute(data, der)
  File "/Users/andfranklin/Projects/sem_python/src/sem_python/aux/VolumeFractionPhase1.py", line 13, in compute
    data[self.name] = data["aA1"] / data["A"]
KeyError: 'A'

======================================================================
ERROR: test (testing.tests.derivatives.aux.EntropyMinimumEnergyFluxDerivativesTester.EntropyMinimumEnergyFluxDerivativesTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/EntropyMinimumEnergyFluxDerivativesTester.py", line 76, in test
    rel_diffs = self.derivatives_tester.checkDerivatives(test_aux, other_aux, root_vars)
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/AuxDerivativesTester.py", line 31, in checkDerivatives
    aux.compute(data, der)
  File "/Users/andfranklin/Projects/sem_python/src/sem_python/aux/VolumeFractionPhase1.py", line 13, in compute
    data[self.name] = data["aA1"] / data["A"]
KeyError: 'A'

======================================================================
ERROR: test (testing.tests.derivatives.aux.EntropyMinimumVolumeFractionFluxDerivativesTester.EntropyMinimumVolumeFractionFluxDerivativesTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/EntropyMinimumVolumeFractionFluxDerivativesTester.py", line 34, in test
    rel_diffs = self.derivatives_tester.checkDerivatives(test_aux, other_aux, root_vars)
  File "/Users/andfranklin/Projects/sem_python/testing/tests/derivatives/aux/AuxDerivativesTester.py", line 32, in checkDerivatives
    test_aux.compute(data, der)
  File "/Users/andfranklin/Projects/sem_python/src/sem_python/aux/EntropyMinimumVolumeFractionFlux.py", line 23, in compute
    l = data["visccoef_aA1"] * data["A"] * data[self.grad_vf]
KeyError: 'A'

======================================================================
ERROR: testJacobianStrong (testing.tests.junctions.equal_solution_lm_1phase_junction.EqualSolutionLM1PhaseJunction.EqualSolutionLM1PhaseJunctionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andfranklin/Projects/sem_python/testing/tests/junctions/equal_solution_lm_1phase_junction/EqualSolutionLM1PhaseJunction.py", line 39, in testJacobianStrong
    self.runDerivativeTest("strong")
  File "/Users/andfranklin/Projects/sem_python/testing/tests/junctions/equal_solution_lm_1phase_junction/EqualSolutionLM1PhaseJunction.py", line 33, in runDerivativeTest
    self.assertTrue(rel_diffs[i,j])
NameError: global name 'rel_diffs' is not defined

======================================================================
ERROR: testJacobianWeak (testing.tests.junctions.equal_solution_lm_1phase_junction.EqualSolutionLM1PhaseJunction.EqualSolutionLM1PhaseJunctionTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/andfranklin/Projects/sem_python/testing/tests/junctions/equal_solution_lm_1phase_junction/EqualSolutionLM1PhaseJunction.py", line 36, in testJacobianWeak
    self.runDerivativeTest("weak")
  File "/Users/andfranklin/Projects/sem_python/testing/tests/junctions/equal_solution_lm_1phase_junction/EqualSolutionLM1PhaseJunction.py", line 33, in runDerivativeTest
    self.assertTrue(rel_diffs[i,j])
NameError: global name 'rel_diffs' is not defined

----------------------------------------------------------------------
Ran 120 tests in 0.594s
```

I'm able to fix the last two by changing line 33 in `testing.tests.junctions.equal_solution_lm_1phase_junction.EqualSolutionLM1PhaseJunction.EqualSolutionLM1PhaseJunctionTester` from `self.assertTrue(rel_diffs[i,j])` to `self.assertTrue(matched[i,j])`.

I'm not sure how to fix the first 3 `KeyError: 'A'` failures.

@jhansel I have two questions:
1. Are these tests failing on the current `master` branch? I would check, but I don't want to setup `sem_python` by polluting my `PYTHONPATH`.
2. If they are not failing on `master`, how can I fix the first 3 `KeyError: 'A'` failures?

**Comment by ghost** [comment]
Sorry for the delay. Something is goofy here. The other day when I pushed
all of those changes (from my home machine), it was passing all of the
tests. Then I come to work, pull, and it's failing the first 3 of the 5
tests you reported failing. The other 2 I just found were probably not seen
to fail because they were not even being run - my tests run script was
looking for the pattern *Tester.py to add tests, and I had mistakenly
omitted the "Tester" part to the file name of this test.

I had some trouble the other day when I was trying out your changes. I
think I found that when I switched back over to master from your branch,
the *.pyc files from your branch stuck around, and were being used instead
of the ones that should be used on master. I believe the new ones were not
generated because I didn't have permission to delete your branch's *.pyc
files (I had to use sudo to remove them). To answer your earlier question,
my OS was Ubuntu (I don't know which version off the top of my head).

Anyway, I want to understand this whole "package" approach before I make
any decisions about your pull request. I haven't had time to look into it
yet. Hopefully you can explore the code as you desire without having the
most recent changes or making new ones yet - it could be a while before
your stuff gets merged. And I don't want to merge it if we cannot address
some of those issues I raised because it would interfere with me being able
to do my job at work.

On a side note, I have been curious about the Julia programming language...
perhaps a sem_julia repo might exist some day :P

**Comment by ghost** [comment]
- I will look into pytest sometime as you suggest.
   - I did see the developer mode option in the README, but there was no
   explanation as to what that entailed, so I ignored it :P
   - I will look into the src/ vs. sem_python/ issue.

**Comment by andfranklin** [comment]
No problem for the delay! My only request is that we get the package restructuring sorted out before you make a lot of changes to your code. Rebasing my branch was not the easiest process. The more changes you make the more difficult it will be. 

---

As far as the testing issues, this is where `setup.py` can come into play. Instead of having to write and maintain your own test runner, `setup.py` handles all of that for you. This means less code for you to keep track of.

---

 I'll try to explain how installing in editable mode  works (`pip install -e .`) :

Whenever you install a package, all of the files files are moved to a default location where all of the other packages (e.g. matplotlib, numpy, etc) are installed. If you (or git) make a change to your package, and you want that to be reflected on the system, you need to reinstall the package.

Whenever you install in editable mode, a link to the package is made in that default location. The result of this is that all of the changes that are made in your package are **automatically** reflected on the system. This is very useful if you are developing code -- this is why it's sometimes referred to as developer mode.

---

So as for the stale `*.pyc` files there are some things that can be done. Before I go into all of that I really think that you should check-out [cookiecutter](https://github.com/audreyr/cookiecutter). It helps you create a python project by setting up all the boiler plate. This is the form that I'm trying to remold `sem_python` into.

---

The "package" approach is confusing, but there are some solid benefits to it. I think it is better to structure your project this way than what you are currently doing. But I understand that you need to use your code to do work. So keep asking questions and I'll try to answer. I'd really like to see sem_python packaged this way.

---

I tinkered with Julia a few years ago -- I haven't used it since. They have some good ideas, but it was immature at the time. Maybe it has changed now?

---

As far as the `src/` vs. `sem_python/`. I've boiled it down to two options:
1. All of the code contained in the top level `sem_python` directory
2. All of the code contained in `src/sem_python`

I tried putting all of the code in a top level `src` directory but this caused errors when testing. The most recent discussions that I've found on the topic recommend option 2 and this is what I'm leaning towards. It is close to what you want, but still clunky.

**Comment by andfranklin** [comment]
If you're worried about performance (I'm assuming this is why you're interested in Julia) there are a lot of things that can be done within python to help with that. You should checkout [numba](https://numba.pydata.org/).

**Pull request closed without merging**
